/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/combatant.glb -o src/components/Combatant.jsx -r public
Author: jakobscheidt (https://sketchfab.com/jakobscheidt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/winter-girl-free-download-f9fc06b8d4044a50a09e75ec3736ac5e
Title: Winter Girl (free download)
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Combatant({ animation, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/combatant.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.24).play();
    return () => actions?.[animation]?.fadeOut(0.24);
  }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Accessoires}
        />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Arms} />

        <mesh geometry={nodes.Object_4.geometry} material={materials.Chest} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Coat} />
        <lineSegments
          geometry={nodes.Object_6.geometry}
          material={materials.Coat_Fur}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Coat_Fur}
        />
        <lineSegments
          geometry={nodes.Object_8.geometry}
          material={materials.Hair}
        />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Hair} />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Luggage}
        />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Mask} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Shoes} />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.Trousers_Skirt}
        />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Head} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Tools} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/combatant.glb");
